# Generated by Django 4.2.2 on 2023-06-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='frontend_projects')),
                ('github_link', models.URLField()),
                ('live_link', models.URLField()),
                ('types', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('both', 'Frontend and Backend')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BackendProject',
        ),
        migrations.DeleteModel(
            name='FrontendProject',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
