# Generated by Django 4.2.2 on 2023-07-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contact_icon_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='types',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('both', 'Frontend and Backend')], default='frontend', max_length=100),
        ),
    ]
