# Generated by Django 5.2.6 on 2025-10-08 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('build_number', models.IntegerField()),
                ('download_url', models.URLField()),
                ('checksum', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('release_notes', models.TextField()),
                ('is_critical', models.BooleanField(default=False)),
                ('minimum_version', models.CharField(blank=True, max_length=20, null=True)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-build_number'],
                'unique_together': {('version', 'build_number')},
            },
        ),
    ]
