# Generated by Django 5.2.6 on 2025-10-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationversion',
            name='download_url',
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='updates/'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
